name: giro
description: "Exploring map app"
publish_to: "none"
version: 1.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  duration: ^4.0.3
  equatable: ^2.0.5
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_slidable: ^4.0.0
  geolocator: ^13.0.2
  intl: ^0.19.0
  map_launcher: ^3.5.0
  mmkv: ^1.3.9
  objective_c: ^2.0.0
  platform_maps_flutter: ^1.0.2

dev_dependencies:
  ffigen: ^14.0.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

dependency_overrides:
  apple_maps_flutter:
    git:
      url: https://github.com/Anjula/apple_maps_flutter.git
      ref: cb853b3f3b86b3453559bf35f632696bb0357234

flutter:
  uses-material-design: true
